//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Infraestructura.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.CuentaClientes = new HashSet<CuentaCliente>();
        }
    
        public System.Guid ClienteId { get; set; }
        public int NroCliente { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string DNI { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string DomicilioParticular { get; set; }
        public string DomicilioComercial { get; set; }
        public string NroCelular { get; set; }
        public string TelefonoFijo { get; set; }
        public string Rubro { get; set; }
        public System.Guid ZonaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaCliente> CuentaClientes { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
