//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Infraestructura.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public System.Guid FacturaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public System.Guid CuentaClienteId { get; set; }
    
        public virtual CuentaCliente CuentaCliente { get; set; }
    }
}
