//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Infraestructura.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public System.Guid MovimientoId { get; set; }
        public decimal Importe { get; set; }
        public int Operacion { get; set; }
        public decimal DebeFechaOperacion { get; set; }
        public decimal HaberFechaOperacion { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public System.Guid CuentaClienteId { get; set; }
    
        public virtual CuentaCliente CuentaCliente { get; set; }
    }
}
