//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Infraestructura.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public System.Guid ProductoId { get; set; }
        public decimal MontoTotalCancelar { get; set; }
        public string Descripcion { get; set; }
        public System.Guid RelacionProductosPlane_ProductosPlanesId { get; set; }
    
        public virtual RelacionProductosPlane RelacionProductosPlane { get; set; }
    }
}
