//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Infraestructura.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionProductosPlane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelacionProductosPlane()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public System.Guid ProductosPlanesId { get; set; }
        public System.DateTime FechaInicioPlanPago { get; set; }
        public System.DateTime FechaEstimadaCancelacion { get; set; }
        public bool DeudaCancelada { get; set; }
        public decimal AlicuotaSemanal { get; set; }
        public System.Guid PlanId { get; set; }
        public System.Guid CuentaClienteCuentaClienteId { get; set; }
    
        public virtual CuentaCliente CuentaCliente { get; set; }
        public virtual Plan Plane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
